Update build-kernel-a14-5.15.yml

diff --git a/.github/workflows/build-kernel-a14-5.15.yml b/.github/workflows/build-kernel-a14-5.15.yml
--- a/.github/workflows/build-kernel-a14-5.15.yml
+++ b/.github/workflows/build-kernel-a14-5.15.yml
@@ -6,6 +6,12 @@ on:
       lto_type:
         required: true
         type: string
+      next_branch:
+        required: true
+        type: string
+      next_branch_custom:
+        required: false
+        type: string
   
 jobs:
   build-kernel-a14-5-15-kernelsu-susfs:
@@ -155,13 +161,26 @@ jobs:
           $REPO --version
           $REPO --trace sync -c -j$(nproc --all) --no-tags --fail-fast
 
+      - name: Determine the branch for kernelsu
+        run: |
+          if [[ "${{ inputs.next_branch }}" == "Stable" ]]; then
+            echo "BRANCH=Stable" >> $GITHUB_ENV
+          elif [[ "${{ inputs.next_branch }}" == "Dev" ]]; then
+            echo "BRANCH=Dev-next" >> $GITHUB_ENV
+          elif [[ "${{ inputs.next_branch }}" == "Other" && -n "${{ inputs.next_branch_custom }}" ]]; then
+            echo "BRANCH=${{ inputs.next_branch_custom }}" >> $GITHUB_ENV
+          else
+            echo "Error: Custom branch not provided for 'Other'" >&2
+            exit 1
+          fi
+
       - name: Add KernelSU
         run: |
           echo "Changing to configuration directory: $CONFIG..."
           cd "$CONFIG"
           
           echo "Adding KernelSU..."
-          curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -
+          curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash $BRANCH
 
       - name: Apply SUSFS Patches
         run: |
